spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
  security:
    user:
      name: admin
      password: qwer1234
      roles: ADMIN
logging:
  config: classpath:log4j2.xml
debug: false
#server:
#  error:
#    path: "/404"
---
# debug
spring:
  config:
    activate:
      on-profile: debug
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=sarangbang;trustServerCertificate=true;encrypt=true;
    username: sa
    password: rudnf12dnjf
    batis:
      jdbc-url: jdbc:sqlserver://localhost;databaseName=sarangbang;trustServerCertificate=true;encrypt=true;
      username: sa
      password: rudnf12dnjf

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 300m
logging:
  file:
    path: logs/sarangbang
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
file:
  path: D:/tmp
  excelPath: D:\101.source\Intellij\web\sarangbang\src\main\resources\excel\
  refPath: classpath:/excel/

---
# mysql (mariadb)
spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    database-platform: ??
  datasource:
    url: ??
    username: sa
    password: rudnf12dnjf
    batis:
      jdbc-url: ??
      username: sa
      password: rudnf12dnjf
server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 30m
---
# mssql
spring:
  config:
    activate:
      on-profile: mssql
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=sarangbang;trustServerCertificate=true;encrypt=true;
    username: sa
    password: rudnf12dnjf
    batis:
      jdbc-url: jdbc:sqlserver://localhost;databaseName=sarangbang;trustServerCertificate=true;encrypt=true;
      username: sa
      password: rudnf12dnjf
server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 30m