spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
  security:
    user:
      name: admin
      password: qwer1234
      roles: ADMIN
logging:
  config: classpath:log4j2.xml
debug: false
---
# debug
spring:
  config:
    activate:
      on-profile: debug
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=sarangbang;trustServerCertificate=true;encrypt=true;
    username: sa
    password: rudnf12dnjf
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 300m
---
# release
spring:
  config:
    activate:
      on-profile: release
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=sarangbang;trustServerCertificate=true;encrypt=true;
    username:
    password:
server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 30m